<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'Cryptum\\Checkout\\Utils\\Api' => $baseDir . '/src/Utils/Api.php',
    'Cryptum\\Checkout\\Utils\\Log' => $baseDir . '/src/Utils/Log.php',
);
