<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitce2c641db7e4e0c20113a0db8aa97378
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'Cryptum\\Checkout\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Cryptum\\Checkout\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Cryptum\\Checkout\\Utils\\Api' => __DIR__ . '/../..' . '/src/Utils/Api.php',
        'Cryptum\\Checkout\\Utils\\Log' => __DIR__ . '/../..' . '/src/Utils/Log.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitce2c641db7e4e0c20113a0db8aa97378::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitce2c641db7e4e0c20113a0db8aa97378::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitce2c641db7e4e0c20113a0db8aa97378::$classMap;

        }, null, ClassLoader::class);
    }
}
